#pragma once

enum UNIT_NEW_STATUS {
	
	UNIT_NEW_STATUS_GRAVITY = 0x0E,
	UNIT_NEW_STATUS_ExposeDef = 0x12,
	UNIT_NEW_STATUS_ExposeRes = 0x10,
	UNIT_NEW_STATUS_Brave = 0x11,
	UNIT_NEW_STATUS_Avoid = 0x0F,
	UNIT_NEW_STATUS_AvoidPlus = 0x13,
	UNIT_NEW_STATUS_UpperStance = 0x14,
	UNIT_NEW_STATUS_ClearStance = 0x15,
	UNIT_NEW_STATUS_SwiftStance = 0x16,
	
};